car_project/__init__.py
from flask import Flask

from config import Config

app = Flask(__name__)


app.config.from_object(Config)

car_project/templates/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/getdata')
def getdata():
    return { 'some': 'value'}

car_project/templates/authentication/routes.py
from flask import Blueprint, render_template


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    return render_template('signup.html')

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    return render_template('signin.html')

car_project/templates/authentication/auth_templates/signin.html
{% extends 'base.html' %}

{% block content %}

    <h1>Login In Here</h1>

{% endblock content %}

car_project/templates/authentication/auth_templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Sign Up Here</h1>
{% endblock content %}

car_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Inventory API</title>
</head>
<body>

        <!--NavBar Here-->
        <nav class="ct-nav">
            <div>
                <img src="../static/images/Coding Drones Logo.png" alt="Cars Inventory Logo">
            </div>

            <!--Nav Items-->
            <div>
                <ul id="horizontal-list">
                    <a href="">
                        <li>The C.I.A. project</li>
                    </a>
                    <a href="">
                        <li>Help Us Grow</li>
                    </a>
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <!--User Auth Check for SignIn/SignUp Nav Buttons-->

                    <a href="">
                        <li>Log Out</li>
                    </a>

                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>

                </ul>
            </div>
          </nav>
          <!--End of Nav-->

          {% block content %}
          {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>